### ISSUE TITLE
invalid ELF header

### ISSUE THREAD

**Issue by codingchili** [codingchili/kibana-mithril#29]
Reported from kibana-mithril.com
===
Hi, I am unable to install this 2FA with version 6.6.0 of Kibana.

Initially using the default kbn-authentication-plugin.zip package, I ran into the error message 6.6.0 is not compatible with 6.3.2. Thus, I changed the version from 6.3.2 to 6.6.0 in the package.json file.

I reran the plugin installation and this time the following error message showed up:  FATAL  Error: /usr/share/kibana/plugins/kbn-authentication-plugin/node_modules/ref-napi/build/Release/binding.node: invalid ELF header

Please let me know if there is anything I am doing incorrectly and what needs to be corrected for me to make this work. Thank you for your help!

**Comment by FrancDeGir** [comment]
I had the same problem. This is due to the fact that 'node_modules' in this package made for Windows. You need to remove the 'node_modules' directory and rebuild it under Linux. Repack and try again. 

But at me on Ubuntu Server 16.04 gives the following error:
 FATAL  Error: Optimizations failure.
   5058 modules
    
    ERROR in ./plugins/kbn-authentication-plugin/public/app.jade 2:10
    Module parse failed: Unexpected token (2:10)
    You may need an appropriate loader to handle this file type.
    | style
    >   include style/style.css
    |   include style/app.css
    | 

I don't know what to do next...

**Comment by codingchili** [comment]
Thanks for the info.

@FrancDeGir which version of Kibana are you using?

**Comment by FrancDeGir** [comment]
@codingchili tried on 6.5.4 and 6.6.0 version.

**Comment by codingchili** [comment]
I'm trying on 6.6.0 now, not able to install the plugin. It seems to get stuck while "optimizing browser bundles." Maybe I just need more verbose logging.

**Comment by FrancDeGir** [comment]
I have all kiabna error log.

[Kibana_Error_Log.txt](https://github.com/codingchili/kibana-mithril/files/2855897/Kibana_Error_Log.txt)

**Comment by codingchili** [comment]
Thanks!.

There's a lot of related issues
https://github.com/babel/babel-loader/issues/173 

Maybe there's some webpack configuration bundled with kibana that needs a poke.

Also, there's a bunch of plugin related issues to check  
https://github.com/elastic/kibana/issues/19678
https://github.com/elastic/kibana/issues/6495

I will try to reproduce with more verbose logging and under Linux.

**Comment by codingchili** [comment]
@FrancDeGir opened #32 for the loader issue.

Closing this as we are going to automate releases of windows/unix builds.
