### ISSUE TITLE
kibana-mithril 1.2.1 (6.6.0 or 7.0.0-beta1) will not install on kibana 6.6.1

### ISSUE THREAD

**Issue by stephgosling** [codingchili/kibana-mithril#45]
Probably a trivial thing but the documentation leads me to believe that 1.2.1 will install on kibana 6.6.0 _or newer_, but it apparently does not:
```
bash-4.2$ kibana-plugin install 'https://github.com/codingchili/kibana-mithril/releases/download/1.2.1/mithril-GNU.Linux-x86_64-6.6.0.zip'
Found previous install attempt. Deleting...
Attempting to transfer from https://github.com/codingchili/kibana-mithril/releases/download/1.2.1/mithril-GNU.Linux-x86_64-6.6.0.zip
Transferring 14397613 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Plugin kibana-mithril [6.6.0] is incompatible with Kibana [6.6.1]"
bash-4.2$ kibana-plugin install 'https://github.com/codingchili/kibana-mithril/releases/download/1.2.1/mithril-GNU.Linux-x86_64-7.0.0-beta1.zip'
Attempting to transfer from https://github.com/codingchili/kibana-mithril/releases/download/1.2.1/mithril-GNU.Linux-x86_64-7.0.0-beta1.zip
Transferring 14397620 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Plugin kibana-mithril [7.0.0] is incompatible with Kibana [6.6.1]"
```

**Comment by codingchili** [comment]
Hello @stephgosling 

Kibana plugins are pinned to each minor version, this forces us to create a dist for each release. Even if it's just minor bugfixes.

You may download the 6.6.0 version distribution zip and edit the following in kibana/kibana-mithril/package.json

```
"kibana": {
    "version": "6.6.0"
  },
```

set version to 6.6.1 and replace the file in the zip. Local plugin archives can be installed with the `file:///` protocol. example `kibana-plugin install file:///...`. Alternatively clone the repository, edit package.json and run the build script.

I will replace 6.6.0 with 6.6.1 in the build matrix

Regards,
Robin

**Comment by codingchili** [comment]
Reference to some discussion on the topic.

https://github.com/elastic/kibana/issues/9019#issuecomment-259451144

Basically the plugin system wasn't mature two years ago to follow semver. It still isn't and even bugfix releases may break compatibility.

**Comment by codingchili** [comment]
And also, I will look over the documentation to bring clarity to this.

**Comment by codingchili** [comment]
@stephgosling updated the 1.2.1 release with a build for 6.6.1. GNU/Linux builds are done, still waiting for the windows build to complete.

**Comment by stephgosling** [comment]
@codingchili amazing thank you! I was hacking at the zipfile but couldn't work out out to get the kibana-plugin to read a local file, I should have tried `file://` but I didn't. Thanks very much for the quick turnaround!

**Comment by codingchili** [comment]
Thanks for the update, closing this issue. 👍

**Comment by stephgosling** [comment]
@codingchili amazing thank you! I was hacking at the zipfile but couldn't work out out to get the kibana-plugin to read a local file, I should have tried `file://` but I didn't. Thanks very much for the quick turnaround!
