### ISSUE TITLE
After installed plugin,kibana could not start service

### ISSUE THREAD

**Issue by tuohaibei** [codingchili/kibana-mithril#46]
Hi @codingchili 
When i install plugin like this(linux system)
./kibana-plugin https://github.com/codingchili/kibana-mithril/releases/download/1.2.0/mithril-GNU.Linux-x86_64-6.6.0.zip.

It show installed succesfully.
I also configured config.json. and when I started the kibana service, it failed to start successfully.
Kibana version:6.6.0
Eleasisearch version:6.6.0

**Comment by codingchili** [comment]
Hello,

I need some more information. Are there any errors in the kibana logs? Could you try running it directly from the bin folder?

**Comment by tuohaibei** [comment]
I start and stop service like this:
sudo systemctl start kibana.service
sudo systemctl stop kibana.service

Releated page is so:https://www.elastic.co/guide/en/kibana/current/start-stop.html

**Comment by tuohaibei** [comment]
it could start service.But when i login using file way.it has the following error
![image](https://user-images.githubusercontent.com/5082315/54300810-9d9c8f80-45f8-11e9-9653-b45d2aa30d22.png)

**Comment by codingchili** [comment]
It's an error with the native dependency on argon2, used for hashing passwords.

I could check it on Linux again, you could try cloning and building the zip on the same system.

**Comment by tuohaibei** [comment]
I have fixed the issue,thanks.it was caused by my wrong configs about config file.
