### ISSUE TITLE
incompatible version

### ISSUE THREAD

**Issue by tuohaibei** [codingchili/kibana-mithril#49]
I use kibana 6.7.1.which version do i need install plugin?i have install 6.6.1 and 7.0.It shows incompatible

![image](https://user-images.githubusercontent.com/5082315/56730514-c59c1880-678a-11e9-9050-154fcf3e576a.png)

**Comment by codingchili** [comment]
Hello @tuohaibei 

There are no prebuilt distributions for 6.7.1, you could use the latest 6.6.x release and just update the version in the archive, it's in the package.json file. Or checkiut the repository and build with the script.
