### ISSUE TITLE
How to Remove Old 2FA Device and Register New One?

### ISSUE THREAD

**Issue by yongyct** [codingchili/kibana-mithril#53]
Hi,

Was using the mithril plugin integrated with my AD, and was able to set up the environment fine.

Unfortunately, one of the users had to have their phone undergo factory reset, resulting in the old device being no longer valid. 

How can I delete the old 2FA device and let the AD user register a new one?

Thanks

**Comment by codingchili** [comment]
Hello,

When using AD for authentication, 2FA secrets are stored on disk using the file storage.

The path to the file is configured in config.json, the default value is `"file": "users.json"`

To reset 2FA you need to stop the Kibana server, edit users.json and set `verified: false` and the user should then be able to register the key again. 

If anyone wants to submit a PR for this, 
1. Add a file listener on user.json to reload it on change.
2. Create a utility script for clearing the verified flag on secrets.

This would make it possible to reset 2Fa codes without restarting the server.

BR // Robin
